SELECT
    T1.ROOM_NAME,
    T1.ORGANIZER,
    MIN(T2.START_DATE) AS EARLIEST_CLASH_DATE,
    COUNT(*) AS CLASH_COUNT
FROM
    ROOM_BOOKINGS T1
INNER JOIN
    ROOM_BOOKINGS T2
ON
    T1.ROOM_NAME = T2.ROOM_NAME
    AND T1.ORGANIZER != T2.ORGANIZER
    AND T1.START_DATE <= T2.END_DATE
    AND T1.END_DATE >= T2.START_DATE
GROUP BY
    T1.ROOM_NAME,
    T1.ORGANIZER
HAVING
    COUNT(*) > 1
ORDER BY
    EARLIEST_CLASH_DATE ASC;